# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_auto_20170205_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=63)),
                ('slug', models.SlugField(help_text='A label for URL config.', unique=True)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
            options={
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.AlterUniqueTogether(
            name='poem',
            unique_together=set([('title', 'author')]),
        ),
    ]
