# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_poem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='categories.Category'),
        ),
    ]
