# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.CharField(help_text='A label for URL config.', max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
