# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 23:45
from __future__ import unicode_literals

from django.db import migrations

CATEGORIES = (
    # (category name, slug)
    ("absurd", "absurd"),
    ("fantasy", "fantasy"),
    ("marrige", "marrige"),
    ("ode", "ode"),
    ("other", "other"),
    ("real", "real"),
    ("romantic", "romantic"),
    ("sadness", "sadness"),
    ("science fiction", "science-fiction"),
)

class Migration(migrations.Migration):

    def add_category_data(apps, schema_editor):
        Category = apps.get_model('categories', 'Category')
        for name, slug in CATEGORIES:
            Category.objects.create(name=name, slug=slug)

    def remove_category_data(apps, schema_editor):
        Category = apps.get_model('categories', 'Category')
        for _, slug in CATEGORIES:
            category = Category.objects.get(slug=slug)
            category.delete()

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_category_data, remove_category_data)
    ]
