# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(help_text='A label for URL config', max_length=63, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('ordering', 'parent_list')]),
        ),
    ]
