# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 07:35
from __future__ import unicode_literals

from django.db import migrations
from datetime import date

LISTS = [
    {'title': 'books',
     'slug': 'books',
     'pub_date': date(2016, 12, 30),
     },
    {'title': 'favourite foods',
     'slug': 'favourite-foods',
     'pub_date': date(2017, 1, 2),
     },
    {'title': 'programming languages',
     'slug': 'programming-languages',
     'pub_date': date(2017, 1, 4),
     },
    {'title': 'benefits of water',
     'slug': 'water-benefits',
     'pub_date': date(2017, 1, 15),
     },
    {'title': 'french tanks',
     'slug': 'french-tanks',
     'pub_date': date(2017, 1, 20),
     },
    {'title': 'top sci-fi games',
     'slug': 'top-sf-games',
     'pub_date': date(2017, 2, 1),
     },
    {'title': 'hollywood artists',
     'slug': 'hollywood-artists',
     'pub_date': date(2017, 2, 8),
     },
]

class Migration(migrations.Migration):

    def add_list_data(apps, schema_editor):
        List = apps.get_model('lists', 'List')
        for list_item in LISTS:
            list_object = List.objects.create(
                title=list_item['title'],
                slug=list_item['slug'])
            list_object.pub_date=list_item['pub_date']
            list_object.save()
        

    def remove_list_data(apps, schema_editor):
        List = apps.get_model('lists', 'List')
        for list_item in LISTS:
            list_object = List.objects.get(slug=list_item['slug'])
            list_object.delete()

    dependencies = [
        ('lists', '0002_auto_20170211_0734'),
    ]

    operations = [
        migrations.RunPython(add_list_data, remove_list_data)
    ]
