# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 08:04
from __future__ import unicode_literals

from django.db import migrations

ITEMS = [
    {'text': 'Lord of the Rings\n'
     'This is my favourite book of all time. '
     'Written by J. R. R. Tolkien, british author.\n'
     'I can really recommend to everyone.',
     'parent_list': 'books',
     'ordering': 1,
     },
    {'text': 'Harry Potter',
     'parent_list': 'books',
     'ordering': 2,
     },
    {'text': 'Gone with the Wind\n'
     'I will read it.',
     'parent_list': 'books',
     'ordering': 3,
     },
    {'text': 'Watson\'s w40k books\n'
     'Great grim-dark books for all the fans. Warhammer 40.000, of course.',
     'parent_list': 'books',
     'ordering': 4,
     },
    {'text': 'pasta',
     'parent_list': 'favourite-foods',
     'ordering': 1,
     },
    {'text': 'steak',
     'parent_list': 'favourite-foods',
     'ordering': 2,
     },
    {'text': 'meatballs',
     'parent_list': 'favourite-foods',
     'ordering': 3,
     },
    {'text': 'Python\n\nMy main language.\nThis site is written in Django, '
     'a Python web framework.',
     'parent_list': 'programming-languages',
     'ordering': 1,
     },
    {'text': 'Perl\n\nMy first ever programming language. It\'s like a camel.',
     'parent_list': 'programming-languages',
     'ordering': 2,
     },
    {'text': 'Healthy and hidrating.',
     'parent_list': 'water-benefits',
     'ordering': 1,
     },
    {'text': 'AMX 13-90\n\n'
     'light tank',
     'parent_list': 'french-tanks',
     'ordering': 1,
     },
    {'text': 'Sauma\n\n'
     'medium tank',
     'parent_list': 'french-tanks',
     'ordering': 2,
     },
    {'text': 'Bat-chat 25t\n\n'
     'I don\'t care what',
     'parent_list': 'french-tanks',
     'ordering': 3,
     },
    {'text': 'Mass effect 1',
     'parent_list': 'top-sf-games',
     'ordering': 1,
     },
    {'text': 'Mass effect 3',
     'parent_list': 'top-sf-games',
     'ordering': 2,
     },
    {'text': 'Mass effect 2',
     'parent_list': 'top-sf-games',
     'ordering': 3,
     },
    {'text': 'Actory McActorface',
     'parent_list': 'hollywood-artists',
     'ordering': 1,
     },
]


class Migration(migrations.Migration):

    def add_items_data(apps, schema_editor):
        List = apps.get_model('lists', 'List')
        Item = apps.get_model('lists', 'Item')
        for item in ITEMS:
            item_object = Item.objects.create(
                text=item['text'],
                ordering=item['ordering'],
                parent_list=List.objects.get(slug=item['parent_list']))

    def remove_items_data(apps, schema_editor):
        Item = apps.get_model('lists', 'Item')
        for item in ITEMS:
            item_object = Item.objects.get(text=item['text'])
            item_object.delete()

    dependencies = [
        ('lists', '0003_lists_data'),
    ]

    operations = [
        migrations.RunPython(add_items_data, remove_items_data)
    ]
