# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify

SLUG_LENGTH = 63

class Migration(migrations.Migration):

    def add_slug_data(apps, schema_editor):
        Snippet = apps.get_model('snippets', 'Snippet')
        query = Snippet.objects.all()
        for snippet in query:
            excepted_slug = slugify(snippet.title)
            if snippet.title == '':
                snippet.slug = slugify(snippet.id)
            else:
                snippet.slug = excepted_slug
            snippet.save()

    def remove_slug_data(apps, schema_editor):
        Snippet = apps.get_model('snippets', 'Snippet')
        Snippet.objects.update(slug='')

    dependencies = [
        ('snippets', '0004_auto_20170206_2039'),
    ]

    operations = [
        migrations.AddField(model_name='snippet',name='slug',
                            field=models.SlugField(max_length=SLUG_LENGTH,
                                                   default=''),
                            ),
        migrations.RunPython(add_slug_data, reverse_code=remove_slug_data),
        migrations.AlterField(model_name='snippet',name='slug',
                              field=models.SlugField(max_length=SLUG_LENGTH),
                              ),
    ]
