# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('snippets', '0006_auto_20170206_2212'), ('snippets', '0007_auto_20170206_2215'), ('snippets', '0008_auto_20170206_2241')]

    dependencies = [
        ('snippets', '0005_snippet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.CharField(blank=True, max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=63, unique=True),
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-create_date']},
        ),
    ]
