# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:53
from __future__ import unicode_literals

from datetime import date
from django.db import migrations

NEWSLINKS = [
    {
        "title": "Redundant Homepage Link",
        "link": "http://jambonsw.com",
        "pub_date": date(2013, 1, 18),
        "startup": 'jambon-software',
    },
    {
        "title": "Monkey (Wikipedia)",
        "link": "https://en.wikipedia.org/wiki/Monkey",
        "pub_date": date(2012, 7, 22),
        "startup": "monkey-software",
    },
    {
        "title": "William Shakespeare (Wikipedia)",
        "link": "https://en.wikipedia.org/wiki/William_Shakespeare",
        "pub_date": date(2014, 4, 26),
        "startup": "monkey-software",
    },
]


class Migration(migrations.Migration):

    def add_newslink_data(apps, schema_editor):
        NewsLink = apps.get_model('organizer', 'NewsLink')
        Startup = apps.get_model('organizer', 'Startup')
        for newslink in NEWSLINKS:
            newslink_object = NewsLink.objects.create(
                title=newslink['title'],
                link=newslink['link'],
                pub_date=newslink['pub_date'],
                startup=Startup.objects.get(slug=newslink['startup']))

    def remove_newslink_data(app, schema_editor):
        NewsLink = apps.get_model('organizer', 'NewsLink')
        for newslink in NEWSLINKS:
            newslink_object = NewsLink.objects.get(slug=newslink['slug'])
            newslink_object.delete()

    dependencies = [
        ('organizer', '0003_startup_data'),
    ]

    operations = [
        migrations.RunPython(add_newslink_data, remove_newslink_data)
    ]
